port 1194
proto udp
dev tun

# Caminhos para os teus ficheiros
topology subnet
ca /etc/openvpn/server/ca.cert.pem
cert /etc/openvpn/server/gateway.cert.pem
key /etc/openvpn/server/gateway.key.pem
dh /etc/openvpn/server/dh.pem
#Rede do túnel VPN (sub-rede virtual)
server 10.8.0.0 255.255.255.0

# Rota para a rede interna [cite: 14]
push "route 10.60.0.0 255.255.255.0"

keepalive 10 120
cipher AES-256-GCM
auth SHA256
persist-key
persist-tun

# Logs para ver se há erros
#status /var/log/openvpn-status.log
verb 3

# Autenticação 2FA (Username/Password + Google Authenticator)
# Vamos configurar isto a seguir
plugin /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so openvpn
